# H A M K A D E H
# _________________________________________
# Logging on Hamkadeh
POST http://192.168.134.10:8002/web_requests/h/login/
Content-Type: application/json

{
    "username": "aeshraghi",
    "password": "123456",
    "type": "sms"
}

# "type": "voip"

###
# HAMKADEH: Supplier missedcalls
###
POST http://192.168.134.10:8002/web_requests/h/c_sup/?username=aeshraghi
Content-Type: application/json

{

}

###



# 5 0 4 0
# _________________________________________
# Logging on 5040
POST http://192.168.134.10:8002/web_requests/5/login/
Content-Type: application/json

{
    "username": "aeshraghi",
    "password": "123456",
    "type": "test"
}

###
#
# Archive
POST http://192.168.134.10:8002/web_requests/archive/?username=aeshraghi
Content-Type: application/json


[
{
	"company": "5040",
	"name": "call/logs/list",
	"directory_helper": "",
	"body": {},
	"query": {
		"report": 1,
		"filter": 1,
		"startCallDate": "1404/06/07 00:00:00",
		"endCallDate": "1404/06/07 23:59:59"
	}
},
{
	"company": "Hamkadeh",
	"name": "call-log/index",
	"directory_helper": "",
	"body": {},
	"query": {
		"export_data": 1,
		"start_call_from": "1404/06/07 00:00:00",
		"start_call_to": "1404/06/07 23:59:59"
	}
},
{
	"company": "Hamkadeh",
	"name": "factor/index",
	"directory_helper": "ثبت",
	"body": {},
	"query": {
		"export_data": 1,
		"start_created_at": "1404/06/07 00:00:00",
		"end_created_at": "1404/06/07 23:59:59"
	}
},
{
	"company": "Hamkadeh",
	"name": "factor/index",
	"directory_helper": "وصول",
	"body": {},
	"query": {
		"export_data": 1,
		"start_accept_action_date": "1404/06/07 00:00:00",
		"end_accept_action_date": "1404/06/07 23:59:59",
		"receipt_status": "accepted ",
		"status": "PAID"
	}
},
{
	"company": "5040",
	"name": "factors/list",
	"directory_helper": "ثبت",
	"body": {},
	"query": {
		"report": 1,
		"filter": 1,
		"startInvoiceDate": "1404/06/07 00:00:00",
		"endInvoiceDate": "1404/06/07 23:59:59"
	}
},
{
	"company": "5040",
	"name": "factors/list",
	"directory_helper": "وصول",
	"body": {},
	"query": {
		"report": 1,
		"filter": 1,
		"startPayAcceptDate": "1404/06/07 00:00:00",
		"endPayAcceptDate": "1404/06/07 23:59:59",
		"payStatus": "paid"
	}
},
{
	"company": "5040",
	"name": "v1/extraction",
	"directory_helper": "",
	"integration_days_num": {
		"year": 0,
		"month": 0,
		"day": 1,
		"hour": 0,
		"minute": 0,
		"second": 0
	},        
	"body": {
		"containDeletedEntries": true,
		"startEntryDate": "1404/06/07 00:00:00",
		"references": ["Landing", "sms"],
		"endEntryDate": "1404/06/07 23:59:59"
	},
	"query": {}
}
]



###
#
# 5040Home
# Opening Home
GET http://192.168.134.10:8002/web_requests/5/open_home/?username=aeshraghi
Content-Type: application/json

###



# Overal Reports
# _________________________________________

# Noname
POST http://192.168.134.10:8002/web_requests/noname/?username=aeshraghi
Content-Type: application/json



###
# Scenario



###
#Incoming numbers

