# H A M K A D E H
# _________________________________________
# Logging on Hamkadeh
POST http://192.168.134.10:8002/web_requests/h/login/
Content-Type: application/json

{
    "username": "aeshraghi",
    "password": "123456",
    "type": "sms"
}

# "type": "voip"

###
# HAMKADEH: Supplier missedcalls
###
POST http://192.168.134.10:8002/web_requests/h/c_sup/?username=aeshraghi
Content-Type: application/json

{

}

###



# 5 0 4 0
# _________________________________________
# Logging on 5040
POST http://192.168.134.10:8002/web_requests/5/login/
Content-Type: application/json

{
    "username": "aeshraghi",
    "password": "123456",
    "type": "test"
}

###
#
# Archive
POST http://192.168.134.10:8002/web_requests/archive/?username=aeshraghi
Content-Type: application/json

[
    {
        "company": "Hamkadeh",
        "name": "factor/index",
        "directory_helper": "وصول",
        "body": {},
        "query": {
        "export_data": 1,
        "start_accept_action_date": "1404/05/04 00:00:00",
        "end_accept_action_date": "1404/05/04 23:59:59",
        "receipt_status": "accepted ",
        "status": "PAID"
    }
  }    
]


###
#
# 5040Home
# Opening Home
GET http://192.168.134.10:8002/web_requests/5/open_home/?username=aeshraghi
Content-Type: application/json

###
#