# Generated by Django 5.1.4 on 2025-01-25 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_requests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestlog',
            name='file_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
