# Generated by Django 5.1.4 on 2025-02-04 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_requests', '0003_alter_requestlog_response_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestlog',
            name='execution_time',
            field=models.DurationField(null=True),
        ),
        migrations.AddField(
            model_name='requestlog',
            name='request_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
