# Generated by Django 5.1.4 on 2025-02-08 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_requests', '0005_requests'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestlog',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='log', to='web_requests.requests'),
        ),
    ]
