# Generated by Django 5.1.4 on 2025-02-24 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_requests', '0007_requests_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestlog',
            name='request_data',
            field=models.JSONField(null=True),
        ),
    ]
