# Generated by Django 4.2 on 2025-03-15 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_requests', '0008_alter_requestlog_request_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Web_Auth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('token', models.CharField(max_length=200, null=True)),
                ('loginExpire', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
