# Generated by Django 4.2 on 2025-03-15 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_requests', '0009_web_auth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='web_auth',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
