# Generated by Django 4.2 on 2025-03-15 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_remove_user_web_auth'),
        ('web_requests', '0010_alter_web_auth_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='web_auth',
            name='web_auth',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.user'),
        ),
    ]
