# Generated by Django 4.2 on 2025-03-16 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_requests', '0011_web_auth_web_auth'),
    ]

    operations = [
        migrations.RenameField(
            model_name='web_auth',
            old_name='loginExpire',
            new_name='value',
        ),
        migrations.RemoveField(
            model_name='web_auth',
            name='token',
        ),
    ]
