# Generated by Django 4.2 on 2025-03-16 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_remove_user_web_auth'),
        ('web_requests', '0012_rename_loginexpire_web_auth_value_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebTokens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('value', models.CharField(max_length=200, null=True)),
                ('web_auth', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.user')),
            ],
        ),
        migrations.DeleteModel(
            name='Web_Auth',
        ),
    ]
