# Generated by Django 4.2 on 2025-03-16 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_requests', '0013_webtokens_delete_web_auth'),
    ]

    operations = [
        migrations.RenameField(
            model_name='webtokens',
            old_name='web_auth',
            new_name='username',
        ),
    ]
