# Generated by Django 4.2 on 2025-03-16 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_remove_user_web_auth'),
        ('web_requests', '0014_rename_web_auth_webtokens_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webtokens',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.user'),
        ),
    ]
