# Generated by Django 4.2 on 2025-03-16 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_remove_user_web_auth'),
        ('web_requests', '0015_alter_webtokens_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='webtokens',
            old_name='username',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='webtokens',
            unique_together={('user', 'name')},
        ),
    ]
