# Generated by Django 4.2 on 2025-04-26 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_requests', '0016_rename_username_webtokens_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webtokens',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
