# Generated by Django 4.2 on 2025-05-07 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_companies'),
        ('web_requests', '0017_alter_webtokens_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='request', to='common.companies'),
            preserve_default=False,
        ),
    ]
