# Generated by Django 4.2 on 2025-05-07 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_requests', '0018_requests_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requests',
            name='company',
        ),
    ]
