# Generated by Django 4.2 on 2025-05-07 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_companies'),
        ('web_requests', '0019_remove_requests_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestsForeign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('endpoint', models.URLField()),
                ('method', models.CharField(max_length=10)),
                ('body_parameters', models.JSONField(blank=True, null=True)),
                ('query_parameters', models.JSONField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request', to='common.companies')),
            ],
        ),
    ]
