# Generated by Django 4.2 on 2025-05-07 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_requests', '0020_requestsforeign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requests',
            name='url',
            field=models.URLField(),
        ),
    ]
