# Generated by Django 4.2 on 2025-05-07 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_companies'),
        ('web_requests', '0021_alter_requests_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestsforeign',
            name='headers',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requestsforeign',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='common.companies'),
        ),
        migrations.AlterField(
            model_name='requestsforeign',
            name='method',
            field=models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('DELETE', 'DELETE')], max_length=10),
        ),
        migrations.AlterField(
            model_name='requestsforeign',
            name='name',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
