# Generated by Django 4.2 on 2025-05-08 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_companies'),
        ('web_requests', '0022_requestsforeign_headers_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='requestsforeign',
            unique_together={('company', 'name')},
        ),
    ]
