# Generated by Django 4.2 on 2025-03-15 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_requests', '0010_alter_web_auth_name'),
        ('common', '0003_alter_user_web_auth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='web_auth',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='web_requests.web_auth'),
        ),
    ]
