# Generated by Django 4.2 on 2025-03-15 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_alter_user_web_auth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='web_auth',
        ),
    ]
