# Generated by Django 5.1.4 on 2025-02-05 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=200)),
                ('method', models.CharField(max_length=10)),
                ('header', models.TextField()),
                ('body', models.TextField()),
                ('request_time', models.DateTimeField()),
                ('response', models.TextField()),
                ('duration', models.DurationField()),
                ('status', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduledRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=200)),
                ('method', models.CharField(max_length=10)),
                ('header', models.TextField()),
                ('body', models.TextField()),
            ],
        ),
    ]
