# Generated by Django 5.1.4 on 2025-02-08 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RequestLog',
            new_name='RequestSchedulerLog',
        ),
        migrations.DeleteModel(
            name='ScheduledRequest',
        ),
    ]
